cafe_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('create/', views.order_create, name='order_create'),
    path('<int:order_id>/', views.order_detail, name='order_detail'),
    path('<int:order_id>/update/', views.order_update, name='order_update'),
    path('<int:order_id>/delete/', views.order_delete, name='order_delete'),
    path('revenue/', views.calculate_revenue, name='revenue'),
    # API endpoints
    path('api/orders/', views.order_list_api, name='order_list_api'),
    path('api/orders/create/', views.order_create_api,
         name='order_create_api'),
    path('api/orders/<int:order_id>/', views.order_detail_api,
         name='order_detail_api'),
    path('api/orders/<int:order_id>/update/', views.order_update_api,
         name='order_update_api'),
    path('api/orders/<int:order_id>/delete/', views.order_delete_api,
         name='order_delete_api'),
]

orders/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models


class MenuItem(models.Model):
    """
    Модель для представления блюда в меню.
    """
    name = models.CharField(
        max_length=255,
        verbose_name=('Название блюда'),)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name=('Стоимость'),
        validators=[MinValueValidator(Decimal('0.00'))])

    def __str__(self):
        return f"{self.name} - {self.price} руб."


class Order(models.Model):
    """
    Модель для представления заказа.
    """
    STATUS_CHOICES = [
        ('pending', 'В ожидании'),
        ('ready', 'Готово'),
        ('paid', 'Оплачено'),
    ]
    table_number = models.IntegerField(
        validators=[MinValueValidator(1)],
        verbose_name=('Номер стола'),)
    items = models.ManyToManyField(
        MenuItem,
        related_name='orders',
        through='OrderItem',
        verbose_name=('Блюда стола'),)
    total_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0,
        verbose_name=('Сумма стола'),
        validators=[MinValueValidator(Decimal('0.00'))])
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        verbose_name=('Статус стола'),
        default='pending')

    def save(self, *args, **kwargs):
        """
        Сохраняет заказ и обновляет общую стоимость.
        """
        created = not self.pk
        super().save(*args, **kwargs)
        if not created and hasattr(self, 'orderitem_set'):
            self.total_price = sum(
                order_item.menu_item.price * order_item.quantity
                for order_item in self.orderitem_set.all())
            super().save(*args, **kwargs)

    def __str__(self):
        return (f'Order #{self.id} - Table {self.table_number} - '
                f'{self.get_status_display()} - ${self.total_price}')


class OrderItem(models.Model):
    """
    Модель для представления элемента заказа.
    """
    order = models.ForeignKey(
          Order,
          on_delete=models.CASCADE)
    menu_item = models.ForeignKey(
          MenuItem,
          on_delete=models.CASCADE,
          verbose_name=('Блюдо со стоимостью'),)
    quantity = models.PositiveIntegerField(
          default=1,
          verbose_name=('Колличество'),)

    def __str__(self):
        return f"{self.menu_item.name} x{self.quantity}"

orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Order, OrderItem


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['menu_item', 'quantity']


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['table_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['table_number'].widget.attrs['placeholder'] = (
            'Введите номер стола')

    def clean_table_number(self):
        table_number = self.cleaned_data.get('table_number')
        if table_number:
            existing_orders = Order.objects.filter(
                table_number=table_number,
                status__in=['pending', 'ready'])
            if existing_orders.exists():
                raise ValidationError(
                    f'Стол {table_number} ещё не оплачен.')
        return table_number


class OrderUpdateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['table_number', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['table_number'].widget.attrs['placeholder'] = (
            'Введите номер стола'
        )

orders/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.db.models import Sum
from django.forms import formset_factory
from django.db import IntegrityError

from .models import Order, MenuItem, OrderItem
from .forms import OrderCreateForm, OrderItemForm, OrderUpdateForm


def calculate_total_price(order):
    """
    Вычисляет общую стоимость заказа на основе элементов заказа.
    """
    return sum(oi.quantity * oi.menu_item.price
               for oi in order.orderitem_set.all())


def order_list(request):
    """
    Отображает список всех заказов
    с возможностью фильтрации по номеру стола и статусу.
    """
    search_query = request.GET.get('search', '')
    search_type = request.GET.get('search_type', '')
    status_mapping = {
        'В ожидании': 'pending',
        'Готово': 'ready',
        'Оплачено': 'paid',
    }
    orders = Order.objects.all()
    if search_query:
        if search_type == 'table_number':
            orders = orders.filter(table_number__icontains=search_query)
        elif search_type == 'status':
            internal_status = status_mapping.get(search_query)
            if internal_status:
                orders = orders.filter(status=internal_status)
            else:
                orders = Order.objects.none()
    return render(request, 'orders/order_list.html', {
        'orders': orders,
        'search_query': search_query,
        'search_type': search_type
    })


def order_create(request):
    """
    Обрабатывает создание нового заказа.
    """
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            table_number = data.get('table_number')
            if table_number is None:
                return JsonResponse({
                    'status': 'error',
                    'message': 'Номер стола обязателен к заполнению'
                }, status=400)
            items_data = data.get('items', [])
            if not items_data:
                return JsonResponse({
                    'status': 'error',
                    'message': 'Заказ не может быть создан без блюда'
                    }, status=400)
            existing_order = Order.objects.filter(
                table_number=table_number,
                status__in=['pending', 'ready']
            ).first()
            if existing_order:
                return JsonResponse({
                    'status': 'error',
                    'message': f'Стол {table_number} занят.'
                               f'Существующий заказ ID: {existing_order.id}.'
                }, status=400)
            form = OrderCreateForm({'table_number': table_number})
            if not form.is_valid():
                return JsonResponse(
                    {'status': 'error', 'errors': form.errors}, status=400)
            order = form.save(commit=False)
            order.status = 'pending'
            order.save()
            for item_data in items_data:
                menu_item_id = item_data.get('menu_item')
                quantity = item_data.get('quantity')
                if menu_item_id and quantity:
                    try:
                        OrderItem.objects.create(
                            order=order,
                            menu_item_id=menu_item_id,
                            quantity=quantity)
                    except IntegrityError:
                        return JsonResponse({
                            'status': 'error',
                            'message': f'Блюдо с ID {menu_item_id} не найдено'
                             }, status=400)
            order.total_price = calculate_total_price(order)
            order.save()
            return JsonResponse({
                'status': 'success',
                'message': 'Order created',
                'order_id': order.id
            }, status=201)
        except (KeyError, ValueError) as e:
            return JsonResponse(
                {'status': 'error', 'message': str(e)}, status=400)
    else:
        form = OrderCreateForm()
        return render(request, 'orders/order_create.html', {
            'form': form,
            'menu_items': MenuItem.objects.all()
        })


def order_detail(request, order_id):
    """
    Отображает детали конкретного заказа по его идентификатору.
    """
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'orders/order_detail.html', {'order': order})


def order_update(request, order_id):
    """
    Обрабатывает обновление существующего заказа.
    """
    order = get_object_or_404(Order, pk=order_id)
    formset = formset_factory(OrderItemForm, can_delete=True)
    if request.method == 'POST':
        form = OrderUpdateForm(request.POST, instance=order)
        order_items_form = formset(request.POST)
        if form.is_valid() and order_items_form.is_valid():
            order = form.save()
            order.orderitem_set.all().delete()
            for order_item_form in order_items_form:
                if order_item_form.cleaned_data:
                    order_item = order_item_form.save(commit=False)
                    order_item.order = order
                    order_item.save()
            order.total_price = calculate_total_price(order)
            order.save()
            if order.status == 'paid':
                calculate_revenue()
            return redirect('orders:order_list')
    else:
        form = OrderUpdateForm(instance=order)
        order_items = order.orderitem_set.all()
        initial_data = [{'menu_item': item.menu_item,
                         'quantity': item.quantity} for item in order_items]
        order_items_form = formset(initial=initial_data)
    return render(request, 'orders/order_update.html', {
        'form': form,
        'order_items_form': order_items_form,
        'order': order,
        'menu_items': MenuItem.objects.all()
    })


def order_delete(request, order_id):
    """
    Обрабатывает удаление заказа по его идентификатору.
    """
    order = get_object_or_404(Order, pk=order_id)
    if request.method == 'POST':
        order.delete()
        return redirect('orders:order_list')
    return render(request, 'orders/order_delete.html', {'order': order})


def calculate_revenue(request=None):
    """
    Вычисляет общую выручку от оплаченных заказов.
    """
    revenue = Order.objects.filter(status='paid').aggregate(
        total_revenue=Sum('total_price'))
    if request:
        return render(request, 'orders/revenue.html', {
            'revenue': revenue['total_revenue'] or 0
        })
    return revenue['total_revenue'] or 0


def order_list_api(request):
    """
    Возвращает список всех заказов в формате JSON.
    """
    orders = Order.objects.all()
    data = [{
        'id': order.id,
        'table_number': order.table_number,
        'items': [{
            'name': item.menu_item.name,
            'price': str(item.menu_item.price),
            'quantity': item.quantity
        } for item in order.orderitem_set.all()],
        'total_price': str(order.total_price),
        'status': order.get_status_display()
    } for order in orders]
    return JsonResponse(data, safe=False)


def order_create_api(request):
    """
    Обрабатывает создание нового заказа через API.
    """
    if request.method == 'POST':
        order_form = OrderCreateForm(request.POST)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.status = 'pending'
            order.save()
            items_data = request.POST.getlist("items")
            for item_data in items_data:
                menu_item_id, quantity = map(int, item_data.split('_'))
                OrderItem.objects.create(order=order,
                                         menu_item_id=menu_item_id,
                                         quantity=quantity)
            order.total_price = calculate_total_price(order)
            order.save()
            return JsonResponse({'status': 'success',
                                 'message': 'Order created'}, status=201)
        return JsonResponse({'status': 'error',
                             'errors': order_form.errors}, status=400)
    return JsonResponse({'status': 'error',
                         'message': 'Invalid method'}, status=405)


def order_detail_api(request, order_id):
    """
    Возвращает детали конкретного заказа в формате JSON.
    """
    order = get_object_or_404(Order, pk=order_id)
    data = {
        'id': order.id,
        'table_number': order.table_number,
        'items': [{
            'name': item.menu_item.name,
            'price': str(item.menu_item.price),
            'quantity': item.quantity
        } for item in order.orderitem_set.all()],
        'total_price': str(order.total_price),
        'status': order.get_status_display()
    }
    return JsonResponse(data)


def order_update_api(request, order_id):
    """
    Обрабатывает обновление существующего заказа через API.
    """
    order = get_object_or_404(Order, pk=order_id)
    if request.method == 'PUT':
        order_form = OrderUpdateForm(request.POST, instance=order)
        if order_form.is_valid():
            order = order_form.save()
            OrderItem.objects.filter(order=order).delete()
            items_data = request.POST.getlist('items')
            for item_data in items_data:
                menu_item_id, quantity = map(int, item_data.split('_'))
                OrderItem.objects.create(order=order,
                                         menu_item_id=menu_item_id,
                                         quantity=quantity)
            order.total_price = calculate_total_price(order)
            order.save()
            if order.status == 'paid':
                calculate_revenue()
            return JsonResponse({'status': 'success',
                                 'message': 'Order updated'}, status=200)

orders/templates/orders/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Главная страница</title>
    <style>
        body { font-family: sans-serif; margin: 20px; }
        .section { margin-bottom: 20px; }
        .last-orders { border: 1px solid #ddd; padding: 10px; }
        .last-orders h2 { margin-top: 0; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h1>Добро пожаловать в систему управления рестораном</h1>
    <div class="section">
        <h2>Последние заказы (в ожидании):</h2>
        <div class="last-orders">
            {% if last_orders %}
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Номер стола</th>
                            <th>Общая стоимость</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in last_orders %}
                            <tr>
                                <td>{{ order.id }}</td>
                                <td>{{ order.table_number }}</td>
                                <td>{{ order.total_price }} руб.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Нет текущих заказов.</p>
            {% endif %}
        </div>
    </div>
    <div class="section">
        <h2>Общая выручка:</h2>
        <p>{{ total_revenue }} руб.</p>
    </div>
</body>
</html>

orders/templates/orders/order_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создать заказ</title>
    <style>
        body { font-family: sans-serif; margin: 20px; }
        form { width: 50%; margin: auto; padding: 20px; border: 1px solid #ddd; }
        label { display: block; margin-bottom: 5px; }
        input[type="number"], textarea, select { width: calc(100% - 10px); padding: 8px; margin-bottom: 10px; border: 1px solid #ddd; }
        button { padding: 10px 20px; background-color: #007bff; color: white; border: none; cursor: pointer; }
        button:hover { background-color: #0056b3; }
        .errorlist { color: red; margin-bottom: 10px; }
        .item-form { display: flex; align-items: center; margin-bottom: 10px; }
        .item-form label { margin-right: 10px; }
        .item-form select, .item-form input { flex-grow: 1; padding: 8px; border: 1px solid #ddd; }
        .add-item-button { padding: 10px 20px; background-color: #28a745; color: white; border: none; cursor: pointer; }
        .add-item-button:hover { background-color: #218838; }
         .delete-item-button { padding: 5px 10px; background-color: #dc3545; color: white; border: none; cursor: pointer; margin-left: 5px;}
        .delete-item-button:hover { background-color: #c82333; }
    </style>
</head>
<body>
    <h1>Создать новый заказ</h1>
    <form id="order-form">
        {% csrf_token %}
        {% if form.errors %}
            <ul class="errorlist">
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        <label for="id_table_number">Номер стола:</label>
        {{ form.table_number }}

        <div id="item-form-container">
        </div>
         <button type="button" id="add-item">Добавить блюдо</button>
         <button type="button" id="create-order">Создать заказ</button>
         <a href="{% url 'orders:order_list' %}">Отмена</a>
    </form>
    <script>
         document.getElementById('add-item').addEventListener('click', function() {
              let container = document.getElementById('item-form-container');
              let template = document.createElement('div');
              template.classList.add('item-form');
                template.style.display = "flex";
              template.innerHTML = `
                <label>Блюдо:</label>
                <select class="menu-item" name="menu_item">
                    {% for item in menu_items %}
                    <option value="{{ item.id }}">{{ item.name }} - {{ item.price }} руб.</option>
                     {% endfor %}
               </select>
                <label>Количество:</label>
                <input type="number" class="quantity" value="1" min="1">
                <button type="button" class="delete-item-button">Удалить</button>
               `;
               template.querySelector('.delete-item-button').addEventListener('click', function(){
                  template.remove();
                 });
             container.appendChild(template);
        });
      document.getElementById('create-order').addEventListener('click', function() {
            let items = [];
            let table_number = document.querySelector('#id_table_number').value;
            let itemForms = document.querySelectorAll('#item-form-container .item-form');
            itemForms.forEach(form => {
                 let menu_item_select = form.querySelector('.menu-item')
                  let menu_item_id =  menu_item_select.value;
                  let quantity = form.querySelector('.quantity').value;
                items.push({
                    menu_item: menu_item_id,
                    quantity: quantity
                 });
             });
             fetch("{% url 'orders:order_create' %}", {
                  method: 'POST',
                   headers: {
                      'Content-Type': 'application/json',
                     'X-CSRFToken': '{{ csrf_token }}'
                   },
                    body: JSON.stringify({
                         table_number: table_number,
                         items: items
                    })
                })
                 .then(response => {
                     if (response.ok){
                         window.location.href = "{% url 'orders:order_list' %}";
                     }
                     else{
                       response.json().then(data =>{
                          alert(data.message)
                        })

                      }
                    }
                  )
                 .catch(error => {
                  console.error('Error:', error);
                 });
        });
    </script>
</body>
</html>

orders/templates/orders/order_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Удалить заказ</title>
     <style>
         body { font-family: sans-serif; margin: 20px; }
         div { width: 50%; margin: auto; padding: 20px; border: 1px solid #ddd; }
         button { padding: 10px 20px; background-color: #dc3545; color: white; border: none; cursor: pointer; margin-right: 10px;}
        button:hover { background-color: #c82333; }
         a { padding: 10px 20px; border: 1px solid #ccc; text-decoration: none; color: black;}
         a:hover { background-color: #f2f2f2;}
     </style>
</head>
<body>
    <div>
        <h1>Удалить заказ</h1>
        <p>Вы уверены, что хотите удалить заказ №{{ order.id }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Удалить</button>
             <a href="{% url 'orders:order_list' %}">Отмена</a>
        </form>
    </div>
</body>
</html>

orders/templates/orders/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Детали заказа</title>
    <style>
        body { font-family: sans-serif; margin: 20px; }
        .order-details { border: 1px solid #ddd; padding: 20px; margin-bottom: 20px; width: 50%; }
        h2 { margin-bottom: 15px; }
        p { margin-bottom: 10px; }
    </style>
</head>
<body>
    <h1>Детали заказа</h1>
     <div class="order-details">
        <h2>Заказ #{{ order.id }}</h2>
         <p><strong>Номер стола:</strong> {{ order.table_number }}</p>
           <p><strong>Блюда:</strong></p>
             <ul>
              {% for item in order.orderitem_set.all %}
                  <li>{{ item.menu_item.name }}: {{ item.menu_item.price }} x{{item.quantity}}</li>
              {% endfor %}
             </ul>
        <p><strong>Общая стоимость:</strong> {{ order.total_price }} руб.</p>
        <p><strong>Статус:</strong> {{ order.get_status_display }}</p>
           <a href="{% url 'orders:order_list' %}">Назад к заказам</a>
     </div>
</body>
</html>

orders/templates/orders/order_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Заказы</title>
     <style>
        body { font-family: sans-serif; margin: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .search-container { margin-bottom: 10px; }
        .search-container input, .search-container select, .search-container button { padding: 8px; margin-right: 5px; }
        .errorlist { color: red; margin-bottom: 10px; }
        .action-links a { margin-right: 5px; }
         .action-links {white-space: nowrap;}
    </style>
</head>
<body>
    <h1>Заказы</h1>
    <div class="search-container">
        <form method="get">
            <input type="text" name="search" placeholder="Поиск:" value="{{ search_query }}">
            <select name="search_type">
                <option value="table_number" {% if search_type == 'table_number' %}selected{% endif %}>По номеру стола</option>
                <option value="status" {% if search_type == 'status' %}selected{% endif %}>По статусу</option>
            </select>
            <button type="submit">Искать</button>
            <a href="{% url 'orders:order_list' %}">Очистить поиск</a>
        </form>
    </div>
    {% if error %}
        <ul class="errorlist">
               <li>{{ error }}</li>
        </ul>
    {% endif %}
    <a href="{% url 'orders:order_create' %}">Создать новый заказ</a>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Номер стола</th>
                <th>Блюда</th>
                <th>Общая стоимость</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.table_number }}</td>
                    <td>
                         {% for item in order.orderitem_set.all %}
                             {{ item.menu_item.name }}: {{ item.menu_item.price }} x{{item.quantity }} <br>
                          {% endfor %}
                    </td>
                    <td>{{ order.total_price }} руб.</td>
                    <td>{{ order.get_status_display }}</td>
                     <td class="action-links">
                        <a href="{% url 'orders:order_detail' order.id %}">Просмотреть</a> |
                       <a href="{% url 'orders:order_update' order.id %}">Редактировать</a> |
                        <form method="post" action="{% url 'orders:order_delete' order.id %}" style="display: inline;">
                             {% csrf_token %}
                                 <button type="submit" style="background: none; border: none; color: blue; cursor: pointer; padding: 0;">Удалить</button>
                         </form>
                     </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">Нет заказов</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'orders:revenue' %}">Посмотреть выручку</a>
</body>
</html>

orders/templates/orders/order_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактировать заказ</title>
    <style>
        body { font-family: sans-serif; margin: 20px; }
        form { width: 50%; margin: auto; padding: 20px; border: 1px solid #ddd; }
        label { display: block; margin-bottom: 5px; }
        input[type="number"],
        textarea,
        select { width: calc(100% - 10px); padding: 8px; margin-bottom: 10px; border: 1px solid #ddd; }
        button { padding: 10px 20px; background-color: #007bff; color: white; border: none; cursor: pointer; }
        button:hover { background-color: #0056b3; }
        .errorlist { color: red; margin-bottom: 10px; }
        .item-form { display: flex; align-items: center; margin-bottom: 10px; }
        .item-form label { margin-right: 10px; }
        .item-form select, .item-form input { flex-grow: 1; padding: 8px; border: 1px solid #ddd; }
        .add-item-button { padding: 10px 20px; background-color: #28a745; color: white; border: none; cursor: pointer; }
        .add-item-button:hover { background-color: #218838; }
        .delete-item-button { padding: 5px 10px; background-color: #dc3545; color: white; border: none; cursor: pointer; margin-left: 5px;}
        .delete-item-button:hover { background-color: #c82333; }
    </style>
</head>
<body>
    <h1>Редактировать заказ #{{ order.id }}</h1>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
            <ul class="errorlist">
              {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
               {% endfor %}
           </ul>
         {% endif %}
        <label for="id_table_number">Номер стола:</label>
        {{ form.table_number }}
        <label for="id_status">Статус:</label>
       {{ form.status }}
        <div id="item-form-container">
             {{ order_items_form.management_form }}
            {% for form in order_items_form %}
                <div class="item-form" {% if not form.instance.pk %}style="display: flex;"{% endif %}>
                 {{form.id}}
                  <label for="{{form.menu_item.id_for_label}}">Блюдо:</label>
                  {{form.menu_item}}
                  <label for="{{form.quantity.id_for_label}}">Количество:</label>
                  {{form.quantity}}
                  {% if form.instance.pk %}
                    {{ form.DELETE }}
                  {% endif %}
              </div>
            {% endfor %}
        </div>
           <button type="button" id="add-item">Добавить блюдо</button>
        <button type="submit">Сохранить изменения</button>
        <a href="{% url 'orders:order_list' %}">Отмена</a>
         <a href="{% url 'orders:order_list' %}">Назад к заказам</a>
    </form>
     <script>
        document.getElementById('add-item').addEventListener('click', function() {
              let container = document.getElementById('item-form-container');
              let formCount = container.querySelectorAll('.item-form').length;
              let template = document.querySelector('.item-form').cloneNode(true);
              template.querySelectorAll('input, select').forEach(el => {
                  let id = el.id.replace(/-[0-9]+$/, `-${formCount}`);
                  let name = el.name.replace(/-[0-9]+$/, `-${formCount}`);
                  el.id = id;
                  el.name = name;
                   el.value = '';
              });
               template.style.display = "flex";
               let hiddenDeleteInput = template.querySelector('input[id*="DELETE"]');
               if(hiddenDeleteInput){
                 hiddenDeleteInput.value = ''
               }
               container.appendChild(template);
        });
</script>
</body>
</html>

orders/templates/orders/revenue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выручка</title>
      <style>
        body { font-family: sans-serif; margin: 20px; }
        .revenue-container { border: 1px solid #ddd; padding: 20px; width: 30%; margin: auto; }
        h2 { margin-bottom: 15px; }
    </style>
</head>
<body>
   <div class="revenue-container">
        <h2>Общая выручка</h2>
        <p><strong>Общая:</strong> {{ revenue }} руб.</p>
       <a href="{% url 'orders:order_list' %}">Назад к заказам</a>
   </div>
</body>
</html>